### ISSUE TITLE
Empty Cache Option

### ISSUE THREAD

**Issue by keithws** [nico-martin/Advanced-WPPerformance#13]
I ran into an issue when using the minified files. Turns out the cache is not cleared when the option is turned off and back on. It seems reasonable to delete the cache of minified files when the option is turned off or add a clear cache button. I had to use SFTP and manually empty the cache folder, careful to to delete my critical CSS file.

**Comment by nico-martin** [comment]
Hi Keith.
In the Admin Bar on the too of your frontend and admin area you should have a new menu item called WPPerformance where you can clear the cache: https://ps.w.org/advanced-wpperformance/assets/screenshot-1.png?rev=1707485

**Comment by keithws** [comment]
Awesome! Sometimes I can be so blind! Thank you for taking the time to point it out!

**Comment by nico-martin** [comment]
You're welcome :)
