### ISSUE TITLE
[not-a-bug] Two questions about the project (in german)

### ISSUE THREAD

**Issue by gnanet** [nico-martin/Advanced-WPPerformance#2]
Hallo, ich hoffe erstmals, das ich mit deutsch nicht komplett die Kommunikation falsch anfange. Ich finde dein projekt interessant, und bin gespannt wie es sich entwickelt, und wachst.

Vorausgesetzt dein projekt ist ab einem bestimmten fertigkeits-grad auch für andere bestimmt, habe ich zwei gedanken, die vielleicht dir später helfen könnten:

1. Es würde anderen helfen wenn du die kurzbeschreibung des projekts befüllst.
Anstatt:  "No description, website, or topics provided." würde schon "This plugin adds several performance improvements to your WordPress site." ganz gut aussehen.

2. Könntest du unter Description auch kurz zusammenfassen, wieso du dieses projekt angefangen hast, und wie dein plugin von anderen plugins mit ähnlicher funktion unterscheidet?

beste grüsse
Gergö (@gnanet)

**Comment by nico-martin** [comment]
Hallo Gergö,

Ja, mit deutsch bist du richtig ;)
Das Plugin funktioniert eigentlich recht gut und kann problemlos über das WP repo installiert werden:
https://wordpress.org/plugins/advanced-wpperformance/
In dieser Version kann es eigentlich alle wichtigen Perfrormamcemassnahmen. Es wird jedoch nie "fertig" sein, da ich immer auf neue Aspekte oder technologien eingehen möchte.

Welche description meinst du? Ich dachte, ich hätte die überall angepasst.. aber ja, da hast du recht. Eine etwas ausführlichere Beschreibung wäre sicher nicht verkehrt.

Liebe Grüsse,
Nico

**Comment by nico-martin** [comment]
Ah ok, habs gefunden. Danke für den Hinweis 😄
